Repository ReGLOSS/Trackery-Frontserver, pull requests merged in 2025-07, with the labels that each got.

#44 Feature/간편로그인 회원가입 수정
  src/main/java/com/trackery/trackeryfrontserver/domain/oauth/controller/OAuthController.java
  src/main/resources/static/login/js/login.js
  src/main/resources/static/mypage/js/UpdateUserInfo.js
  src/main/resources/static/oauth/css/oauth-popup.css
  src/main/resources/static/oauth/js/close-popup.js
  src/main/resources/static/oauth/js/register-confirm.js
  src/main/resources/templates/oauth/close-popup.html
  src/main/resources/templates/oauth/link-account.html
  src/main/resources/templates/oauth/register-confirm.html
Labels: bug, enhancement

#46 feature/로그인-가입-완료-모달-수정 간편로그인시 회원가입인지 로그인지 모달에서 표시 가능하게 파라미터 추가
  src/main/java/com/trackery/trackeryfrontserver/domain/oauth/controller/OAuthController.java
  src/main/resources/templates/oauth/close-popup.html
Labels: bug

#47 이미지 조회 방식 수정
  src/main/resources/static/album/js/modules/apiService.js
  src/main/resources/static/album/js/modules/eventHandlers.js
  src/main/resources/static/album/js/modules/imageViewer.js
  src/main/resources/static/album/js/modules/uiUpdater.js
  src/main/resources/static/home/js/map.js
Labels: enhancement

#52 Feature/태그 수정
  src/main/resources/static/album/js/modules/imageEditMode.js
  src/main/resources/static/home/css/home.css
  src/main/resources/static/home/js/map.js
  src/main/resources/static/map/js/MapPickerModal.js
  src/main/resources/static/upload/js/ImageUploadV2.js
Labels: enhancement

#56 Feature/지도 문제 해결
  src/main/resources/static/album/js/modules/imageEditMode.js
  src/main/resources/static/home/js/map.js
  src/main/resources/static/map/css/map-picker-modal.css
  src/main/resources/static/map/js/MapPickerModal.js
  src/main/resources/static/upload/js/ImageUploadV2.js
Labels: bug, enhancement

#57 Feature/지도 좌표표시
  src/main/resources/static/home/css/home.css
  src/main/resources/static/home/js/home.js
  src/main/resources/static/home/js/imageManager.js
  src/main/resources/static/home/js/map.js
  src/main/resources/static/home/js/mapManager.js
  src/main/resources/static/home/js/mapRenderer.js
  src/main/resources/static/home/js/modalManager.js
  src/main/resources/static/home/js/statsRenderer.js
  src/main/resources/static/map/svg/sigungu/busan.svg
  src/main/resources/static/map/svg/sigungu/chungcheongbuk-do.svg
  src/main/resources/static/map/svg/sigungu/chungcheongnam-do.svg
  src/main/resources/static/map/svg/sigungu/daegu.svg
  src/main/resources/static/map/svg/sigungu/daejeon.svg
  src/main/resources/static/map/svg/sigungu/gangwon-do.svg
  src/main/resources/static/map/svg/sigungu/gwangju.svg
  src/main/resources/static/map/svg/sigungu/gyeonggi-do.svg
  src/main/resources/static/map/svg/sigungu/gyeongsangbuk-do.svg
  src/main/resources/static/map/svg/sigungu/gyeongsangnam-do.svg
  src/main/resources/static/map/svg/sigungu/incheon.svg
  src/main/resources/static/map/svg/sigungu/jeju.svg
  src/main/resources/static/map/svg/sigungu/jeollabuk-do.svg
  src/main/resources/static/map/svg/sigungu/jeollanam-do.svg
  src/main/resources/static/map/svg/sigungu/sejong.svg
  src/main/resources/static/map/svg/sigungu/seoul.svg
  src/main/resources/static/map/svg/sigungu/ulsan.svg
  src/main/resources/static/map/svg/simpleSido.svg
  src/main/resources/templates/home.html
Labels: enhancement

#58 Refactor/홈 스타일 수정
  src/main/resources/static/album/css/album-detail.css
  src/main/resources/static/home/css/home.css
  src/main/resources/static/home/js/imageManager.js
  src/main/resources/static/home/js/mapManager.js
  src/main/resources/static/home/js/mapRenderer.js
  src/main/resources/static/home/js/modalManager.js
  src/main/resources/static/home/js/statsRenderer.js
  src/main/resources/static/map/svg/sigungu/busan.svg
  src/main/resources/static/map/svg/sigungu/chungcheongbuk-do.svg
  src/main/resources/static/map/svg/sigungu/chungcheongnam-do.svg
  src/main/resources/static/map/svg/sigungu/daegu.svg
  src/main/resources/static/map/svg/sigungu/daejeon.svg
  src/main/resources/static/map/svg/sigungu/gangwon-do.svg
  src/main/resources/static/map/svg/sigungu/gwangju.svg
  src/main/resources/static/map/svg/sigungu/gyeonggi-do.svg
  src/main/resources/static/map/svg/sigungu/gyeongsangbuk-do.svg
  src/main/resources/static/map/svg/sigungu/gyeongsangnam-do.svg
  src/main/resources/static/map/svg/sigungu/incheon.svg
  src/main/resources/static/map/svg/sigungu/jeju.svg
  src/main/resources/static/map/svg/sigungu/jeollabuk-do.svg
  src/main/resources/static/map/svg/sigungu/jeollanam-do.svg
  src/main/resources/static/map/svg/sigungu/sejong.svg
  src/main/resources/static/map/svg/sigungu/seoul.svg
  src/main/resources/static/map/svg/sigungu/ulsan.svg
  src/main/resources/static/map/svg/simpleSido.svg
  src/main/resources/templates/home.html
Labels: enhancement

#60 Refactor/사이드바 기능 개선
  src/main/resources/static/album/css/album.css
  src/main/resources/static/common/css/layout.css
  src/main/resources/static/common/css/sidebar.css
  src/main/resources/static/home/css/home.css
  src/main/resources/static/mypage/css/mypage.css
  src/main/resources/static/upload/css/image-upload.css
  src/main/resources/templates/common/sidebar.html
Labels: enhancement

#62 Refactor/이미지 업로드 수정 리팩터링
  src/main/resources/static/common/js/landing.js
  src/main/resources/static/home/css/home.css
  src/main/resources/static/home/js/home.js
  src/main/resources/static/home/js/mapManager.js
  src/main/resources/static/home/js/modalManager.js
  src/main/resources/static/map/js/MapPickerModal.js
  src/main/resources/static/module/common/ValidationService.js
  src/main/resources/static/module/common/uiHelpers.js
  src/main/resources/static/module/tags/TagApiService.js
  src/main/resources/static/module/tags/TagManager.js
  src/main/resources/static/module/tags/tagUiManager.js
  src/main/resources/static/mypage/js/MyPage.js
  src/main/resources/static/upload/js/ImageUploadV2.js
  src/main/resources/templates/map/map-picker-modal.html
  src/main/resources/templates/upload/image-upload-content.html
Labels: enhancement
